const AUTH_REGISTER_INIT = 'auth/AUTH_REGISTER_INIT';
const AUTH_REGISTER_SUCCESS = 'auth/AUTH_REGISTER_SUCCESS';

const AUTH_ON_INIT = 'auth/AUTH_ON_INIT';
const AUTH_ON_SUCCESS = 'auth/AUTH_ON_SUCCESS';
const AUTH_ON_ERROR = 'auth/AUTH_ON_ERROR';

const AUTH_LOGIN_INIT = 'auth/AUTH_LOGIN_INIT';
const AUTH_LOGIN_SUCCESS = 'auth/AUTH_LOGIN_SUCCESS';
const AUTH_LOGOUT_SUCCESS = 'auth/AUTH_LOGOUT_SUCCESS';


export default {
  AUTH_REGISTER_INIT,
  AUTH_REGISTER_SUCCESS,
  AUTH_ON_INIT,
  AUTH_ON_SUCCESS,
  AUTH_ON_ERROR,
  AUTH_LOGIN_INIT,
  AUTH_LOGIN_SUCCESS,
  AUTH_LOGOUT_SUCCESS,
};