const AUTH_REGISTER_SUCCESS = 'auth/AUTH_REGISTER_SUCCESS';

const AUTH_ON_INIT = 'auth/AUTH_ON_INIT';
const AUTH_ON_SUCCESS = 'auth/AUTH_ON_SUCCESS';
const AUTH_ON_ERROR = 'auth/AUTH_ON_ERROR';


export default {
  AUTH_REGISTER_SUCCESS,
  AUTH_ON_INIT,
  AUTH_ON_SUCCESS,
  AUTH_ON_ERROR,
};